function fish_greeting
end
fish_vi_key_bindings
set -x JDTLS_HOME /home/jules/.cache/nvim/nvim-lsp/jdtls/
alias bat "batcat"
alias d "dmenu_run"
alias treeMax "exa --tree --icons"
alias tree "exa --tree --level=2 --icons"
alias ll "exa -x -g --icons"
alias lla "exa -x -g -a --icons"
alias dmode "fish_default_key_bindings"
alias vmode "fish_vi_key_bindings"
alias v "nvim "
alias vim "nvim"
alias o "xdg-open"
alias Fzf "fzf --preview='head -$LINES {}' --reverse --bind 'enter:execute(nvim {})'"
alias pullpush "bash ~/code/script/pullpush.sh"
#alias bganimegirl "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/animegirl.jpg"
#alias Bgforestpath "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/forestpath.jpg"
#alias Bgfantazypanorama "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/fantazypanorama.jpg"
#alias BgjapPainting "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/japPainting.jpg"
#alias Bgprettyface "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/prettyface.jpg"
#alias Bgsakuradark "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/sakuradark.jpg"
#alias BgsceneryPainted "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/sceneryPainted.jpeg"
#alias Bgweirdface "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/weirdfacebgred.jpg"
#alias Bgxianxiahug "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/xianxiahug.jpg"
#alias Bgshiro "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/shiro.jpeg"
#alias bgcherryblossom "gsettings set org.gnome.desktop.background picture-uri file:////usr/share/backgrounds/cherryblossom.jpg"
alias BglLake "pkill -f mpv ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/LakeSakura.mp4" 
alias BglRing "pkill -f mpv ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/bluering.mp4" 
alias BglSakura "pkill -f mpv ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/sakura2.mp4" 
alias BglSunset "pkill -f mpv ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/sunset.mp4" 
alias BglSpace "pkill -f mpv ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/space.mp4" 
alias BglFireInSpace "pkill -f mpv ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/fireInSpace.mp4" 
alias Bglsword "pkill -f mpv ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/sword.mp4" 
alias BglLuffy "pkill -f mpv ; sleep 0.5 ; xwinwrap -g 1920x10800 -fs -ov -ni -s -nf -- mpv -wid WID --loop --no-audio /home/jules/Pictures/backgrounds/live_wallpaper/luffy.mp4" 
alias Bgcherryblossom "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/cherryblossom.jpg"
alias Bganimegirl "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/animegirl.jpg"
alias Bgforestpath "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/forestpath.jpg"
alias Bgfantazypanorama "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/fantazypanorama.jpg"
alias BgjapPainting "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/japPainting.jpg"
alias Bgprettyface "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/prettyface.jpg"
alias Bgsakuradark "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/sakuradark.jpg"
alias BgsceneryPainted "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/sceneryPainted.jpg"
alias Bgweirdface "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/weirdfacebgred.jpg"
alias Bgxianxiahug "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/xianxiahug.jpg"
alias Bgcatmeme "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/catMeme.jpg"
alias Bgoldwolverine "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/oldWolverine.jpg"
alias Bgpanda "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/panda.jpg"
alias BgcatForest "pkill -f mpv ; sleep 0.5; feh --bg-scale ~/Pictures/backgrounds/catForest.jpg"

